Programming Assignment #2 - HAPAN, Marianne Guinevere P.

Normalization Problem

In [2]:
import numpy as np

In [13]:
p = np.random.rand(5, 5)

m = p.mean()
s = p.std()

n = (p-m)/s

print("Normalized:", n)

Normalized: [[ 0.68532834  0.8054656  -0.60349966 -1.06563276  0.60347718]
 [ 1.48762474 -1.29785494  1.0283103   1.13078666 -0.66879313]
 [-1.0264505   0.39659893 -1.35826161 -1.28579242 -1.0576153 ]
 [-0.69541634  1.48044348  1.15814569  1.08984818  0.77198024]
 [-1.24406866  0.2135967   0.29808895 -1.33653166  0.49022201]]


Divisible by 3 Problem

In [19]:
d = np.arange(1, 101) ** 2
d = d.reshape(10, 10)

s = d[d % 3 == 0]

print("Array of Squares: ", d)
print("All Elements that are divisible by 3: ", s)

Array of Squares:  [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
All Elements that are divisible by 3:  [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
